swagger: '2.0'

info:
  version: '2.0'
  title: test
  contact:
    name: vitaly
    email: vykont@gmail.com

host: core-content-dev.corebine.com

basePath: /

schemes:
  - http
  - https

consumes:
  - application/json

produces:
  - application/json
